# 特征归一化示例

In [1]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [2]:
#对数据进行归一化
X = np.array([[ 0., 1000.],
                    [ 0.5,  1500.],
                    [ 1.,  2000.]])
min_max_scaler = MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X)
X_minmax

array([[0. , 0. ],
       [0.5, 0.5],
       [1. , 1. ]])

In [3]:
# 将相同的缩放应用到其它数据中
X_test = np.array([[ 0.8, 1800.]])
X_test_minmax = min_max_scaler.transform(X_test)
X_test_minmax

array([[0.8, 0.8]])

In [4]:
# 缩放因子
min_max_scaler.scale_

array([1.   , 0.001])

In [5]:
# 最小值
min_max_scaler.min_

array([ 0., -1.])