In [8]:
# (批大小, 步长数, 序列分量维数)
batch_size = 1
time_step = 2
step_dim = 3

hidden_dim = 2  # 隐藏层维度

### Tensorflow2框架下模拟 

In [ ]:
import tensorflow as tf
import tensorflow.keras as keras

In [2]:
s0 = tf.constant([[0.0, 0.0]]) # 第1步输入的隐状态
x1 = tf.constant([[0.1, 0.2, 0.3]]) # 第1步输入的序列分量
simpleRnnCell = tf.keras.layers.SimpleRNNCell(hidden_dim, use_bias=False)
out1,s1 = simpleRnnCell(x1, [s0]) # 将当前步的x和上一步的隐状态输入到单元中，产生第1步的输出和隐状态
print("out1:", out1)
print("s1:", s1)

out1: tf.Tensor([[-0.3746375   0.00579598]], shape=(1, 2), dtype=float32)
s1: [<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.3746375 ,  0.00579598]], dtype=float32)>]


In [3]:
x2 = tf.constant([[0.2, 0.3, 0.4]]) # 第2步输入的序列分量
out2,s2 = simpleRnnCell(x2, [s1[0]]) # 将当前步的x和上一步的隐状态输入到单元中，产生第2步的输出和隐状态
print("out2:", out2)
print("s2:", s2)

out2: tf.Tensor([[-0.2241037   0.00181398]], shape=(1, 2), dtype=float32)
s2: [<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.2241037 ,  0.00181398]], dtype=float32)>]


#### 下面验证前向传播的计算结果

In [4]:
# 将内部系数全部初始化为1
simpleRnnCell = tf.keras.layers.SimpleRNNCell(hidden_dim, kernel_initializer='ones', 
                                              recurrent_initializer='ones', use_bias=False)

In [5]:
out1,s1 = simpleRnnCell(x1, [s0]) # 将当前步的x和上一步的隐状态输入到单元中，产生第1步的输出和隐状态
print("out1:", out1)
print("s1:", s1)

out1: tf.Tensor([[0.53704965 0.53704965]], shape=(1, 2), dtype=float32)
s1: [<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.53704965, 0.53704965]], dtype=float32)>]


$s_s$为（0，0），$s_x$为（0.6，0.6），因此，$s=tanh(0.6,0.6)$。下面验算一下$tanh(0.6)$

In [6]:
import math
math.tanh(0.6)

0.5370495669980353

可见计算结果是符合预期的。下面给出第2步计算结果，请读者自行验证。

In [7]:
out2,s2 = simpleRnnCell(x2, [s1[0]]) # 将当前步的x和上一步的隐状态输入到单元中，产生第2步的输出和隐状态
print("out2:", out2)
print("s2:", s2)

out2: tf.Tensor([[0.9621513 0.9621513]], shape=(1, 2), dtype=float32)
s2: [<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.9621513, 0.9621513]], dtype=float32)>]


### MindSpore框架下模拟 

MindSpore中实现基本单元的是mindspore.nn.RNNCell，原型如下：
classmindspore.nn.RNNCell(input_size: int, hidden_size: int, has_bias: bool = True, nonlinearity: str = 'tanh')
官网：https://www.mindspore.cn/docs/zh-CN/r1.7/api_python/nn/mindspore.nn.RNNCell.html#mindspore.nn.RNNCell

In [5]:
import mindspore as ms
import mindspore.nn as nn
import numpy as np

In [24]:
net = nn.RNNCell(step_dim, hidden_dim, has_bias=False) # MindSpore框架中的基本单元实现

In [26]:
hx0 = ms.Tensor(np.array([[0.0, 0.0]]).astype(np.float32)) # 第1步输入的隐状态
x1 = ms.Tensor(np.array([[0.1, 0.2, 0.3]]).astype(np.float32)) # 第1步输入的序列分量

In [27]:
hx1 = net(x1, hx0) # # 将当前步的x和上一步的隐状态输入到单元中，产生第1步的隐状态

In [28]:
hx1 # 输出的隐状态是2维大小的

Tensor(shape=[1, 2], dtype=Float32, value=
[[-1.28096893e-001, -1.92629993e-001]])

读者可自行练习书中第二步的馈入与输出。。。