In [1]:
import numpy as np

In [2]:
# 打开文件"traindata.txt"，使用'utf-8'编码
file = open("traindata.txt", encoding='utf-8')

# 初始化两个字典，一个用于存储中文字符及其出现次数，一个用于存储拼音及其出现次数
char_dict = {} # 存储中文字符及出现次数的字典
pinyin_dict = {} # 存储拼音及出现次数的字典

# 读取文件的每一行
lines = file.readlines()

# 使用一个布尔变量tag来切换处理中文字符和拼音的字典
tag = True

# 遍历文件的每一行
for line in lines:
    # 如果tag为True，处理当前行的中文字符，将temp_dict设置为char_dict
    if tag:
        temp_dict = char_dict
        tag = False
    # 否则，处理当前行的拼音，将temp_dict设置为pinyin_dict
    else:
        temp_dict = pinyin_dict
        tag = True

    # 将当前行分割成单词（以空格分隔）
    for cent in line.split():
        # 如果单词已经在temp_dict中，将其计数加1
        if cent in temp_dict:
            temp_dict[cent] += 1
        # 否则，将单词添加到字典中，计数初始化为1
        else:
            temp_dict[cent] = 1      

In [3]:
char_dict# 存储中文字符及出现次数的字典

{'正': 2146,
 '文': 236,
 '第': 753,
 '一': 18660,
 '章': 103,
 '青': 561,
 '衫': 194,
 '磊': 11,
 '落': 545,
 '险': 350,
 '峰': 3140,
 '行': 1340,
 '光': 1040,
 '闪': 403,
 '动': 1294,
 '柄': 186,
 '钢': 215,
 '剑': 1313,
 '倏': 24,
 '地': 2011,
 '刺': 300,
 '出': 4916,
 '指': 1280,
 '向': 2955,
 '在': 6629,
 '年': 1517,
 '汉': 741,
 '子': 6381,
 '左': 1041,
 '肩': 294,
 '使': 846,
 '少': 1983,
 '不': 20022,
 '等': 1281,
 '招': 845,
 '用': 1080,
 '老': 3239,
 '腕': 153,
 '抖': 95,
 '斜': 242,
 '锋': 63,
 '已': 2707,
 '削': 68,
 '那': 6221,
 '右': 743,
 '颈': 134,
 '全': 1262,
 '本': 1388,
 '小': 2914,
 '说': 7112,
 '网': 51,
 '中': 7035,
 '挡': 189,
 '格': 207,
 '铮': 57,
 '的': 18332,
 '声': 4340,
 '响': 605,
 '双': 1118,
 '相': 1895,
 '击': 516,
 '嗡': 34,
 '作': 749,
 '震': 203,
 '未': 823,
 '绝': 514,
 '霍': 45,
 '拆': 75,
 '了': 15287,
 '三': 2135,
 '长': 1638,
 '猛': 254,
 '直': 645,
 '砍': 163,
 '顶': 217,
 '门': 1778,
 '避': 317,
 '侧': 202,
 '手': 5327,
 '诀': 67,
 '引': 186,
 '疾': 168,
 '大': 8968,
 '腿': 232,
 '两': 2393,
 '人': 12535,
 '法': 1450,
 '迅': 84,

In [4]:
print("训练语句用到的字共有", len(char_dict), "个")

训练语句用到的字共有 4205 个


In [5]:
pinyin_dict# 存储拼音及出现次数的字典

{'zheng': 3018,
 'wen': 1896,
 'di': 7006,
 'yi': 28949,
 'zhang': 4490,
 'qing': 5638,
 'shan': 2319,
 'lei': 518,
 'luo': 917,
 'xian': 3330,
 'feng': 4858,
 'xing': 4665,
 'guang': 1175,
 'dong': 2363,
 'bing': 1999,
 'gang': 576,
 'jian': 9855,
 'shu': 3279,
 'ci': 4101,
 'chu': 7302,
 'zhi': 20870,
 'xiang': 9565,
 'zai': 8617,
 'nian': 2076,
 'han': 1347,
 'zi': 13633,
 'zuo': 3344,
 'shi': 35464,
 'shao': 2398,
 'bu': 21830,
 'deng': 2155,
 'zhao': 1978,
 'yong': 1504,
 'lao': 4166,
 'wan': 3252,
 'dou': 2960,
 'xie': 2644,
 'xue': 2289,
 'na': 7216,
 'you': 12723,
 'jing': 4895,
 'quan': 2113,
 'ben': 1939,
 'xiao': 7834,
 'shuo': 7151,
 'wang': 3777,
 'zhong': 11086,
 'dang': 3154,
 'ge': 6963,
 'de': 25005,
 'sheng': 7571,
 'shuang': 1207,
 'ji': 11278,
 'weng': 71,
 'zhen': 2739,
 'wei': 7847,
 'jue': 2184,
 'huo': 1766,
 'chai': 147,
 'le': 14913,
 'san': 2384,
 'chang': 1324,
 'meng': 587,
 'kan': 1485,
 'ding': 2354,
 'men': 4370,
 'bi': 4305,
 'ce': 340,
 'shou': 7144,
 

In [6]:
print("训练语句用到的拼音共有", len(pinyin_dict), "个") # 平均10个汉字对应一个拼音

训练语句用到的拼音共有 415 个


In [7]:
char_id = list(char_dict) # 字典键（中文字符）的列表
# 用列表的下标对汉字进行编号，可用list.index()获取对应汉字的编号，用list[i]获取对应编号i的汉字
print(char_id)
print(char_id[3])

['正', '文', '第', '一', '章', '青', '衫', '磊', '落', '险', '峰', '行', '光', '闪', '动', '柄', '钢', '剑', '倏', '地', '刺', '出', '指', '向', '在', '年', '汉', '子', '左', '肩', '使', '少', '不', '等', '招', '用', '老', '腕', '抖', '斜', '锋', '已', '削', '那', '右', '颈', '全', '本', '小', '说', '网', '中', '挡', '格', '铮', '的', '声', '响', '双', '相', '击', '嗡', '作', '震', '未', '绝', '霍', '拆', '了', '三', '长', '猛', '直', '砍', '顶', '门', '避', '侧', '手', '诀', '引', '疾', '大', '腿', '两', '人', '法', '迅', '捷', '力', '搏', '练', '武', '厅', '东', '坐', '着', '二', '上', '首', '是', '个', '四', '十', '道', '姑', '铁', '脸', '嘴', '唇', '紧', '闭', '下', '五', '余', '岁', '者', '捻', '须', '神', '情', '甚', '得', '意', '座', '位', '距', '丈', '有', '身', '后', '各', '站', '名', '男', '女', '弟', '西', '边', '排', '椅', '宾', '客', '方', '目', '都', '集', '注', '于', '场', '角', '斗', '眼', '见', '与', '到', '七', '越', '来', '兀', '自', '分', '胜', '败', '突', '然', '挥', '微', '幌', '似', '欲', '摔', '跌', '穿', '轻', '忍', '住', '嗤', '笑', '他', '随', '即', '知', '失', '态', '忙', '伸', '按', '口', '便', '这', '时', '呼', '掌', '拍', '心', '前', '跨', '步', '开',

In [8]:
pinyin_id = list(pinyin_dict) # 字典键（拼音）的列表
# 用列表的下标对拼音进行编号
print(pinyin_id)
print(pinyin_id[3])

['zheng', 'wen', 'di', 'yi', 'zhang', 'qing', 'shan', 'lei', 'luo', 'xian', 'feng', 'xing', 'guang', 'dong', 'bing', 'gang', 'jian', 'shu', 'ci', 'chu', 'zhi', 'xiang', 'zai', 'nian', 'han', 'zi', 'zuo', 'shi', 'shao', 'bu', 'deng', 'zhao', 'yong', 'lao', 'wan', 'dou', 'xie', 'xue', 'na', 'you', 'jing', 'quan', 'ben', 'xiao', 'shuo', 'wang', 'zhong', 'dang', 'ge', 'de', 'sheng', 'shuang', 'ji', 'weng', 'zhen', 'wei', 'jue', 'huo', 'chai', 'le', 'san', 'chang', 'meng', 'kan', 'ding', 'men', 'bi', 'ce', 'shou', 'yin', 'da', 'tui', 'liang', 'ren', 'fa', 'xun', 'jie', 'li', 'bo', 'lian', 'wu', 'ting', 'zhe', 'er', 'shang', 'si', 'dao', 'gu', 'tie', 'zui', 'chun', 'jin', 'xia', 'yu', 'sui', 'xu', 'shen', 'ju', 'hou', 'zhan', 'ming', 'nan', 'nv', 'xi', 'bian', 'pai', 'bin', 'ke', 'fang', 'mu', 'zhu', 'yan', 'qi', 'yue', 'lai', 'fen', 'bai', 'tu', 'ran', 'hui', 'huang', 'shuai', 'die', 'chuan', 'chi', 'ta', 'tai', 'mang', 'an', 'kou', 'hu', 'xin', 'qian', 'kua', 'kai', 'mo', 'zhuan', 'he', 'q

In [9]:
# 定义初始概率矩阵pi、转移概率矩阵A和观测概率矩阵B
# 与教材上的处理方式不同，采用全1的平滑处理方式，该处理是符合hmmlearn.hmm的要求。
# 但是这种处理方式简单，仅适合学生入门，效果有时不好。
pi = np.ones(len(char_id))
A = np.ones((len(char_id), len(char_id)))
B = np.ones((len(char_id), len(pinyin_id)))

# 统计3个概率矩阵
n_lines = len(lines)
for i in range(0, n_lines, 2):  # 每两行数据是一组（中文字符和拼音）
    chars = lines[i].split()  # 获取中文字符序列，并使用空格作为分隔符进行分割
    pinyins = lines[i+1].split() # 获取拼音序列，并使用空格作为分隔符进行分割

    # 更新初始概率矩阵pi
    for char in chars:
        if char in char_id:
            pi[char_id.index(char)] += 1

    # 更新观测概率矩阵B
    for j in range(len(chars)):
        if chars[j] in char_id and pinyins[j] in pinyin_id:
            B[char_id.index(chars[j]), pinyin_id.index(pinyins[j])] += 1

    # 更新转移概率矩阵A
    for j in range(len(chars) - 1):
        if chars[j] in char_id and chars[j+1] in char_id:
            A[char_id.index(chars[j]), char_id.index(chars[j+1])] += 1

# 归一化概率矩阵
pi /= np.sum(pi)  
A /= np.sum(A, axis=1, keepdims=True)  # 按列归一化  
B /= np.sum(B, axis=1, keepdims=True)  # 按列归一化

In [10]:
# 计算3个概率矩阵
###  *******************  ###
for i in range(2):
    if np.sum(A[i]) != 0:
        A[i] = A[i] / np.sum(A[i])
print(A)

[[0.00126502 0.00031626 0.00031626 ... 0.00015813 0.00015813 0.00015813]
 [0.00022774 0.00113869 0.00022774 ... 0.00022774 0.00022774 0.00022774]
 [0.00020202 0.00020202 0.00020202 ... 0.00020202 0.00020202 0.00020202]
 ...
 [0.00023776 0.00023776 0.00023776 ... 0.00023776 0.00023776 0.00023776]
 [0.00023781 0.00023781 0.00023781 ... 0.00023781 0.00023781 0.00023781]
 [0.00023776 0.00023776 0.00023776 ... 0.00023776 0.00023776 0.00023776]]


In [11]:
from hmmlearn import hmm
model = hmm.CategoricalHMM(n_components=len(char_id))
###  *******************  ###
### 编写代码完成模型实例化，并导入3个概率矩阵
model.startprob_ = pi
model.emissionprob_ = B
model.transmat_ = A

In [12]:
# !pip install hmmlearn

In [13]:
test = 'duan yu wen ni shi qiao feng hai shi xiao feng' # 因为是用《天龙八部》作为语料库，该句预测较好

In [14]:
# test = 'rong er shi she diao ying xiong chuan li de ren wu '# 该句预测较差

In [15]:
test = test.split()
test_data = []
for i in range(len(test)):
    test_data.append(pinyin_id.index(test[i]))

In [16]:
test_data = np.array(test_data).reshape(-1, 1)
test_out = model.predict(test_data)

In [17]:
test_out_sentence = ""
for id in test_out:
    test_out_sentence += char_id[id]
print(test_out_sentence)
print(test_out)

段誉问你是乔峰还是萧峰
[ 391  492  331  460  100 2624   10  209  100 3423   10]
