## 以数组元素的平方为例示意张量与算子的操作

### numpy计算

In [1]:
import numpy as np
np_x = np.array([1.0, 2.0, 6.0])
print("numpy output = ", np.square(np_x)) # 或者 np_x ** 2；np_x * np_x; np.power(np_x, 2)

numpy output =  [ 1.  4. 36.]


### mindspore计算

In [2]:
import mindspore as ms
import mindspore.ops.operations as P
ms_x = ms.Tensor([1.0, 2.0, 6.0], ms.float32) # 生成一个张量
square = P.Square() # 实例化
output = square(ms_x)
print("mindspore output =", output)

mindspore output = [ 1.  4. 36.]


### tensorflow计算

In [3]:
import tensorflow as tf
tf_x = tf.constant([1.0, 2.0, 6.0])
print("tensorflow output = ", tf.pow(tf_x, 2))

tensorflow output =  tf.Tensor([ 1.  4. 36.], shape=(3,), dtype=float32)


### 对python运算符的支持

In [4]:
print(np_x ** 2)
print(ms_x ** 2)
print(tf_x ** 2)

[ 1.  4. 36.]
[ 1.  4. 36.]
tf.Tensor([ 1.  4. 36.], shape=(3,), dtype=float32)
